### ISSUE TITLE
Getting "No issues found for @kudu"

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-github-issues-prs#6]
![image](https://user-images.githubusercontent.com/22350/27728886-f066b1e6-5d83-11e7-8e5b-77da626a7b9c.png)

**Comment by chrmarti** [comment]
It looks like your Git credentials manager has 'kudu' stored as username. Try setting the username through the setting `github.username`.

**Comment by chrmarti** [comment]
HTH

**Comment by blackjid** [comment]
I'm getting this same error

My git credential manager has the correct username, and the remote from the repo is using https.

I also tried setting the `github.username` but is the same, because the extension is getting the correct username.

I have several issues that I've created or I'm assigned to in that repo. And also the repo is public. 

Any idea?

**Comment by chrmarti** [comment]
@blackjid What is the output of `git remote -v`? And what is the output of `echo "url=REMOTE_URL\n\n" | git credential fill` with REMOTE_URL replaced with your remote? (Careful when posting here, this might include your password.)

**Comment by blackjid** [comment]
```
❯ git remote -v
origin	https://github.com/platanus/potassium.git (fetch)
origin	https://github.com/platanus/potassium.git (push)

❯ echo "url=https://github.com/platanus/potassium.git\n\n" | git credential fill
protocol=https
host=github.com
username=blackjid
password=<my token>
```

**Comment by chrmarti** [comment]
When there are milestones we only search for issues assigned to these. This is tracked as #4.

**Comment by blackjid** [comment]
Perfect, makes sense... thanks

my bad, I didn't read properly the readme. 
> only issues assigned to that user and to the next two milestones are shown.
